version: "3"

services:
  terraform:
    image: hashicorp/terraform:1.3.4
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./:/infra
    working_dir: /infra
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
